# Generated by Django 2.1.4 on 2018-12-08 19:49

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('shortcut', models.CharField(default=django.utils.crypto.get_random_string, max_length=50, unique=True)),
            ],
        ),
    ]
